"""Exact reachable post-lock witness on a leaf-seeded 16-arm star.

The schedule is stated rather than hidden in a gate implementation.  The full
17-vertex star face first appears at stage 4.  Run a requested number of pure
stable-face warmup solves there, then use the full-face momentum beta=33/35.
Up to the first negative trigger there is no retraction, so the trajectory
below is the literal obstacle-prox trajectory generated by this schedule.
"""

from __future__ import annotations

from fractions import Fraction

Rat = Fraction
Vector = list[Rat]
Matrix = list[list[Rat]]


def solve(a: Matrix, b: Vector) -> Vector:
    """Solve a nonsingular rational linear system by exact elimination."""
    n = len(b)
    aug = [row[:] + [rhs] for row, rhs in zip(a, b)]
    for column in range(n):
        pivot = next(row for row in range(column, n) if aug[row][column] != 0)
        aug[column], aug[pivot] = aug[pivot], aug[column]
        scale = aug[column][column]
        aug[column] = [value / scale for value in aug[column]]
        for row in range(n):
            if row == column or aug[row][column] == 0:
                continue
            factor = aug[row][column]
            aug[row] = [
                value - factor * pivot_value for value, pivot_value in zip(aug[row], aug[column])
            ]
    return [row[-1] for row in aug]


def star_instance() -> tuple[Vector, Matrix, Vector, Rat, Rat]:
    """Return degrees, hat Hessian, lower source, kappa, and momentum."""
    arms = 16
    n = arms + 1
    q = Rat(1, 34)
    rho = Rat(1, 64)
    alpha = q * q / (1 + q * q)
    kappa = 1 - 2 * alpha
    beta = (1 - q) / (1 + q)
    degrees = [Rat(arms)] + [Rat(1)] * arms
    qt = [[Rat(0) for _ in range(n)] for _ in range(n)]
    for i, degree in enumerate(degrees):
        qt[i][i] = degree * (1 + alpha) / 2
    edge = -(1 - alpha) / 2
    for leaf in range(1, n):
        qt[0][leaf] = edge
        qt[leaf][0] = edge
    seed = [Rat(0), Rat(1)] + [Rat(0)] * (arms - 1)
    ct = [alpha * seed[i] - alpha * rho * degrees[i] for i in range(n)]
    return degrees, qt, ct, kappa, beta


def obstacle_solve(
    degrees: Vector,
    qt: Matrix,
    ct: Vector,
    kappa: Rat,
    lower_center: Vector,
    warm: list[int],
) -> Vector:
    """Solve the shifted nonnegative quadratic by an exact active-set LCP."""
    n = len(degrees)
    rhs = [ct[i] + kappa * degrees[i] * lower_center[i] for i in range(n)]
    active = set(warm) if warm else {i for i, value in enumerate(rhs) if value > 0}
    if not active:
        active = {i for i, value in enumerate(rhs) if value > 0}
    for _ in range(4 * n + 8):
        index = sorted(active)
        matrix = [[qt[i][j] + (kappa * degrees[i] if i == j else 0) for j in index] for i in index]
        values = solve(matrix, [rhs[i] for i in index])
        negative = [i for i, value in zip(index, values) if value < 0]
        if negative:
            active.difference_update(negative)
            continue
        x = [Rat(0)] * n
        for i, value in zip(index, values):
            x[i] = value
        violations = []
        for i in range(n):
            if i in active:
                continue
            gradient = sum(qt[i][j] * x[j] for j in index) - rhs[i]
            if gradient < 0:
                violations.append(i)
        if not violations:
            return x
        active.update(violations)
    raise RuntimeError("active-set LCP did not terminate")


def run(warmup: int = 4) -> dict[str, object]:
    degrees, qt, ct, kappa, full_beta = star_instance()
    n = len(degrees)
    previous = [Rat(0)] * n
    current = [Rat(0)] * n
    records = []
    momentum_start = 4 + warmup
    for stage in range(momentum_start + 5):
        beta = Rat(0) if stage < momentum_start else full_beta
        velocity = [current[i] - previous[i] for i in range(n)]
        trial = [current[i] + beta * velocity[i] for i in range(n)]
        face = [i for i, value in enumerate(trial) if value > 0]
        trigger = [ct[i] - sum(qt[i][j] * trial[j] for j in range(n)) for i in face]
        negative = [(i, value) for i, value in zip(face, trigger) if value < 0]
        records.append(
            {
                "stage": stage,
                "beta": str(beta),
                "face_size": len(face),
                "minimum_trigger": str(min(trigger)) if trigger else None,
            }
        )
        if negative:
            row, value = negative[0]
            return {
                "q": "1/34",
                "rho": "1/64",
                "seed_leaf": 1,
                "first_full_face_stage": 4,
                "warmup": warmup,
                "warmup_stages": list(range(4, momentum_start)),
                "first_bad_stage": stage,
                "row": row,
                "value": str(value),
                "records": records,
            }
        next_state = obstacle_solve(degrees, qt, ct, kappa, trial, face)
        previous, current = current, next_state
    raise AssertionError("the registered reachable witness was not reproduced")


if __name__ == "__main__":
    results = [run(warmup) for warmup in range(1, 6)]
    expected_four = Rat(
        -282800935773229957572471819375,
        35278895119339184187289463871766528,
    )
    assert [result["first_bad_stage"] for result in results] == [6, 7, 9, 10, 11]
    assert all(result["row"] == 1 for result in results)
    assert Rat(results[3]["value"]) == expected_four
    for result in results:
        print(result)
